Add image label description
harvester/docs pull request #147
Opened 2022-05-05 09:52 UTC by WuJun2016

# links
- https://github.com/harvester/harvester/issues/2057

2022-05-09 07:33 UTC, vickyhella requested changes

2022-05-09 07:33 UTC, vickyhella commented on docs/upload-image.md
> +When you create an image via URL, we will try to add the system-related label automatically, if you create an image by uploading a local file, you will need to select the system type manually.
```suggestion
If you create an image via a URL, we will add the OS type label automatically. However, if you create an image by uploading a local file, you will need to select the OS type manually.
```

2022-05-09 09:35 UTC, WuJun2016 commented on docs/upload-image.md
> +When you create an image via URL, we will try to add the system-related label automatically, if you create an image by uploading a local file, you will need to select the system type manually.
@vickyhella   Done,  PTAL. thanks.

2022-05-09 09:38 UTC, vickyhella commented on docs/upload-image.md
> +When you create an image via URL, we will try to add the system-related label automatically, if you create an image by uploading a local file, you will need to select the system type manually.
LGTM

2022-05-09 09:40 UTC, vickyhella approved these changes

2022-05-12 04:06 UTC, guangbochen requested changes

2022-05-12 04:06 UTC, guangbochen commented on docs/upload-image.md
> +You can add a label for the image, which will help identify the operating system type more accurately.
```suggestion
You can add labels to the image, which will help identify the OS type more accurately. Additionally, you can also add any custom labels when needed.
```

2022-05-12 04:06 UTC, guangbochen commented on docs/upload-image.md
> +If you create an image via a URL, we will add the OS type label automatically. However, if you create an image by uploading a local file, you will need to select the OS type manually.
```suggestion
If you create an image from a URL, the UI will automatically recognize the OS type and image category based on the image name. However, if you created the image by uploading a local file, you will need to manually select the corresponding labels.
```

2022-05-12 04:28 UTC, WuJun2016 commented on docs/upload-image.md
> +If you create an image via a URL, we will add the OS type label automatically. However, if you create an image by uploading a local file, you will need to select the OS type manually.
Done, PTAL again thanks.

2022-05-12 04:38 UTC, guangbochen approved these changes

2022-05-12 04:38 UTC, merged