doc: improve the multi-disk section on host page
harvester/docs pull request #246
Opened 2022-11-15 02:33 UTC by Vicente-Cheng

related issues: #244

2022-11-15 02:46 UTC, vickyhella reviewed
Just a small suggestion, the rest LGTM!

2022-11-15 02:46 UTC, vickyhella commented on docs/host/host.md
> +5. Last, you can check the newly added disk by **⋮ > Edit Config** again. You can also add the NODE/DISK tag this time (Describe detail in the next section).
```suggestion
5. Last, you can check the newly added disk by clicking **⋮ > Edit Config** again. You can also add the NODE/DISK tag this time (details are described in the next section).
```

2022-11-15 03:02 UTC, Vicente-Cheng commented on docs/host/host.md
> +5. Last, you can check the newly added disk by **⋮ > Edit Config** again. You can also add the NODE/DISK tag this time (Describe detail in the next section).
done, thanks!

2022-11-15 03:02 UTC, vickyhella approved these changes

2022-11-16 01:14 UTC, guangbochen commented on docs/host/host.md
> +Now, Harvester does not support adding specific partition as disk. Make sure your disk does not contain any partition or you could not find it at this stage.
Can u please help to double-check the deprecated version, thanks?

2022-11-16 01:19 UTC, Vicente-Cheng commented on docs/host/host.md
> +Now, Harvester does not support adding specific partition as disk. Make sure your disk does not contain any partition or you could not find it at this stage.
Sure, I would like to

2022-11-16 03:42 UTC, Vicente-Cheng commented on docs/host/host.md
> +Now, Harvester does not support adding specific partition as disk. Make sure your disk does not contain any partition or you could not find it at this stage.
I found the UI PR https://github.com/rancher/dashboard/pull/5297
That makes the user only use the whole disk.
And NDM also has some related PR for drop partition mountpoint.
So I thought that we do not support partition after v1.0.2.

2022-11-16 21:58 UTC, btat requested changes
Added a couple small suggestions.

2022-11-16 21:58 UTC, btat commented on docs/host/host.md
> +As of Harvester v1.0.2, we no longer support adding partitions as additional disks. If you want to add it as an additional disk, be sure to reformat it properly first(e.g., using `fdisk`).
```suggestion
As of Harvester v1.0.2, we no longer support adding partitions as additional disks. If you want to add it as an additional disk, be sure to reformat it properly first (e.g., using `fdisk`).
```

2022-11-16 21:58 UTC, btat commented on docs/host/host.md
> +5. Last, you can click **⋮ > Edit Config** again to check the newly added disk. At meanwhile, you can also add the "Host/Disk" tag (details are described in the [next section](#storage-tags)).
```suggestion
5. Last, you can click **⋮ > Edit Config** again to check the newly added disk. Meanwhile, you can also add the "Host/Disk" tag (details are described in the [next section](#storage-tags)).
```

2022-11-17 01:33 UTC, Vicente-Cheng commented on docs/host/host.md
> +As of Harvester v1.0.2, we no longer support adding partitions as additional disks. If you want to add it as an additional disk, be sure to reformat it properly first(e.g., using `fdisk`).
updated, thanks!

2022-11-17 01:34 UTC, Vicente-Cheng commented on docs/host/host.md
> +5. Last, you can click **⋮ > Edit Config** again to check the newly added disk. At meanwhile, you can also add the "Host/Disk" tag (details are described in the [next section](#storage-tags)).
updated!

2022-11-17 01:50 UTC, guangbochen approved these changes
LGTM, thanks.

2022-11-17 01:53 UTC, bk201 approved these changes
LGTM, thanks!

2022-11-17 17:12 UTC, btat approved these changes
LGTM

2022-11-18 07:10 UTC, merged