Fix image positions for the volume section
harvester/docs pull request #370
Opened 2023-07-27 09:56 UTC by vickyhella

Put step-related images right behind the corresponding step to avoid piling up the images.

2023-07-27 18:24 UTC, LucasSaintarbor commented
Hi @vickyhella, thanks for updating these! I noticed some of the images were wrapped with the sentence above for the following pages:

- **Export a Volume to Image** > English v1.1 and v1.2-dev
![Screenshot 2023-07-27 at 11 14 46 AM](https://github.com/harvester/docs/assets/83089978/117e175d-e048-468f-86c0-fef9e1ff1697)


- **Volume Snapshots** > Chines v1.1 and v1.2-dev
![Screenshot 2023-07-27 at 11 19 19 AM](https://github.com/harvester/docs/assets/83089978/4cc7ad3b-a936-4c36-b2d1-e4061b393a92)


- I think we should add a space between the step and the top of the image, as well as the after the image so it doesn't look cluttered. Do you agree?
![Screenshot 2023-07-27 at 11 21 34 AM](https://github.com/harvester/docs/assets/83089978/5f915511-e611-4a96-9f4d-31113891cddd)

2023-07-27 18:25 UTC, LucasSaintarbor requested changes
Added feedback here: https://github.com/harvester/docs/pull/370#issuecomment-1654183081

2023-07-28 03:34 UTC, vickyhella commented
@LucasSaintarbor Thanks for noticing it! 
I've updated this PR using empty lines to separate images and text. Please take a second look and thanks ^^

2023-07-28 19:41 UTC, LucasSaintarbor approved these changes
LGTM, thanks @vickyhella!

2023-07-28 19:42 UTC, merged