Change wording for network requirements from recommendation to required
harvester/docs pull request #377
Opened 2023-08-02 10:23 UTC by Martin-Weiss

For VM migration, for storage replication and for VM access in production scenarios / scenarios under load - 1 GB will not be sufficient at all. Basically with 1 GB the VM migration will not complete if the VM is under load and the automatic and working VM migration will also be required for Harvester upgrades while VMs are up and running.

So we really should change "10 G recommended" to "10 G required".

2023-08-03 06:11 UTC, bk201 approved these changes
Thanks! @guangbochen we also need to adjust the [readme](https://github.com/harvester/harvester#hardware-requirements).

2023-08-03 06:18 UTC, guangbochen commented
Sure I will update it later, @LucasSaintarbor can u PTAL and merge this one AEAP, thanks.

2023-08-07 19:20 UTC, LucasSaintarbor requested changes
Small nics and removed https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fast-enough-for-etcd since the blog is no longer available.

2023-08-07 19:20 UTC, LucasSaintarbor commented on versioned_docs/version-v1.1/install/requirements.md
> +| Network Card     | 1 Gbps Ethernet minimum for testing, 10Gbps Ethernet minimum required for production
```suggestion
| Network Card     | 1 Gbps Ethernet minimum for testing, 10 Gbps Ethernet minimum required for production                                                                                                                       |
```

2023-08-07 19:20 UTC, LucasSaintarbor commented on docs/install/requirements.md
> +| Network Card     | 1 Gbps Ethernet minimum for testing, 10Gbps Ethernet minimum required for production
```suggestion
| Network Card     | 1 Gbps Ethernet minimum for testing, 10 Gbps Ethernet minimum required for production                                                                                                                  |
```

2023-08-07 19:20 UTC, LucasSaintarbor commented on docs/install/requirements.md
>  | Disk Performance | 5,000+ random IOPS per disk(SSD/NVMe). Management nodes (first 3 nodes) must be [fast enough for Etcd](https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fa
```suggestion
| Disk Performance | 5,000+ random IOPS per disk(SSD/NVMe). Management nodes (first 3 nodes) must be fast enough for etcd |
```

2023-08-07 19:20 UTC, LucasSaintarbor commented on versioned_docs/version-v1.1/install/requirements.md
>  | Disk Performance | 5,000+ random IOPS per disk(SSD/NVMe). Management nodes (first 3 nodes) must be [fast enough for Etcd](https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fa
```suggestion
| Disk Performance | 5,000+ random IOPS per disk(SSD/NVMe). Management nodes (first 3 nodes) must be fast enough for etcd |
```

2023-08-08 03:31 UTC, guangbochen commented
> Small nics and removed https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fast-enough-for-etcd since the blog is no longer available.

update to https://www.suse.com/support/kb/doc/?id=000020100 , thanks.

2023-08-08 16:43 UTC, LucasSaintarbor approved these changes
LGTM

2023-08-08 16:44 UTC, merged