Document harvester-csi-hostname limitations
harvester/docs pull request #382
Opened 2023-08-09 18:41 UTC by connorkuehl

2023-08-10 18:40 UTC, LucasSaintarbor requested changes
Lmk if these changes are okay, thanks!

2023-08-10 18:40 UTC, LucasSaintarbor commented on docs/rancher/csi-driver.md
>  - The Harvester virtual machines run as guest Kubernetes nodes are in the same namespace.
```suggestion
- The Harvester virtual machines run as guest Kubernetes nodes in the same namespace.
```

2023-08-10 18:40 UTC, LucasSaintarbor commented on versioned_docs/version-v1.1/rancher/csi-driver.md
>  - The Harvester virtual machines run as guest Kubernetes nodes are in the same namespace.
```suggestion
- The Harvester virtual machines run as guest Kubernetes nodes in the same namespace.
```

2023-08-10 18:40 UTC, LucasSaintarbor commented on docs/rancher/csi-driver.md
> +  of Harvester.
```suggestion
- The Harvester virtual machine guests' hostnames match their corresponding Harvester virtual machine names. Guest cluster Harvester VMs can't have different hostnames than their Harvester VM names when using the Harvester CSI driver. We hope [to remove this limitation](https://github.com/harvester/harvester/issues/4396) in a future release of Harvester.
```

2023-08-10 18:40 UTC, LucasSaintarbor commented on versioned_docs/version-v1.1/rancher/csi-driver.md
> +  of Harvester.
```suggestion
- The Harvester virtual machine guests' hostnames match their corresponding Harvester virtual machine names. Guest cluster Harvester VMs can't have different hostnames than their Harvester VM names when using the Harvester CSI driver. We hope [to remove this limitation](https://github.com/harvester/harvester/issues/4396) in a future release of Harvester.
```

2023-08-14 04:10 UTC, guangbochen approved these changes
LGTM, thanks.

2023-08-15 19:21 UTC, LucasSaintarbor approved these changes
LGTM, thanks!

2023-08-15 19:21 UTC, LucasSaintarbor commented on docs/rancher/csi-driver.md
>  - The Harvester virtual machines run as guest Kubernetes nodes are in the same namespace.
@connorkuehl Makes sense, thank you!

2023-08-16 02:10 UTC, vickyhella approved these changes
LGTM!

2023-08-16 02:11 UTC, merged