install-mode docs
harvester/docs pull request #424
Opened 2023-09-07 00:07 UTC by ibrokethecloud

PR adds a more detailed doc for need for install mode and how to leverage pre-installed install mode raw images.

2023-09-07 08:34 UTC, bk201 commented on docs/install/install-binaries-mode.md
> +### stream disk mode
```suggestion
### Stream disk mode
```

2023-09-07 08:34 UTC, bk201 commented on docs/install/install-binaries-mode.md
> +On `Equinix Metal` the streaming mode can be leverage with the following kernel arguments:
```suggestion
On `Equinix Metal` the streaming mode can be leveraged with the following kernel arguments:
```

2023-09-07 08:34 UTC, bk201 commented on docs/install/install-binaries-mode.md
> +Currently when a new harvester node is launched it needs to be the first node in the cluster or join an existing cluster.
```suggestion
Currently when a new Harvester node is launched it needs to be the first node in the cluster or join an existing cluster.
```
Do we want to make the upper case first letter of Harvester for consistency?

2023-09-07 08:51 UTC, vickyhella requested changes
Some small suggestions on the grammar.

2023-09-07 08:51 UTC, vickyhella commented on docs/install/install-binaries-mode.md
> +On `Equinix Metal` the streaming mode can be leverage with the following kernel arguments:
```suggestion
On `Equinix Metal` the streaming mode can be leveraged with the following kernel arguments:
```

2023-09-07 08:51 UTC, vickyhella commented on docs/install/install-binaries-mode.md
> +This allows better integration with cloud providers.
```suggestion
Harvester has published a raw image artifact for pre-installed Harvester. The Harvester installer now allows streaming a pre-installed image directly to disk to support better integration with cloud providers.
```

2023-09-07 08:51 UTC, vickyhella commented on docs/install/install-binaries-mode.md
> +This allows better integration with cloud providers.
Better give a link to the `raw image artifact`, if any

2023-09-07 08:51 UTC, vickyhella commented on docs/install/install-binaries-mode.md
> +On `Equinix Metal` the streaming mode can be leveraged with the following kernel arguments:
```suggestion
On `Equinix Metal`, you can use the following kernel arguments to use the streaming mode:
```

2023-09-07 08:51 UTC, vickyhella commented on docs/install/install-binaries-mode.md
> +When leveraging streaming of disk, it is recommended to host the raw disk artifact closer to the targets. The raw disk artifact is nearly 16G in size.
```suggestion
When streaming to disk, it is recommended to host the raw disk artifact closer to the targets, as the raw disk artifact is nearly 16G in size.
```

2023-09-07 20:12 UTC, LucasSaintarbor reviewed
+1 Vicky's suggestions

2023-09-08 02:26 UTC, bk201 approved these changes
LGTM, thanks!

2023-09-08 02:26 UTC, vickyhella commented on docs/install/install-binaries-mode.md
> +title: "Install Binaries Only Mode"
```suggestion
sidebar_label: Install Harvester Binaries Only
title: "Install Harvester Binaries Only"
```

2023-09-08 02:27 UTC, vickyhella commented on docs/install/install-binaries-mode.md
> +title: "Install Binaries Only Mode"
Modify the title to stay consistent with the UI.

2023-09-08 02:29 UTC, vickyhella approved these changes
LGTM!

2023-09-08 03:40 UTC, LucasSaintarbor approved these changes
LGTM, thanks!

2023-09-08 06:11 UTC, merged