Add workaroud of fail to enable monitoring addon
harvester/docs pull request #512
Opened 2024-02-19 11:06 UTC by w13915984028

Issue: https://github.com/harvester/harvester/issues/4962

This PR describes the steps to reproduce, troubleshooting and the workaroud to solve.

2024-02-20 01:28 UTC, bk201 approved these changes
lgtm from tech perspective

2024-02-20 09:00 UTC, jillian-maroket commented on docs/troubleshooting/monitoring.md
> +- Longhorn manager fails to schedule the replica.
```suggestion
- Longhorn Manager is unable to schedule the replica.
```

2024-02-20 09:02 UTC, jillian-maroket commented on docs/troubleshooting/monitoring.md
> +1. Select `Edit YAML` from the right side **⋮** pop up menu of `rancher-monitoring` on **Addon** page.
```suggestion
1. On the **Addons** screen of the Harvester UI, select **⋮** (menu icon) and then select **Edit YAML**.
```

2024-02-20 09:07 UTC, jillian-maroket commented on docs/troubleshooting/monitoring.md
> +- The POD `prometheus-rancher-monitoring-prometheus-0` in `cattle-monitoring-system` namespace fails to start due to PVC attached failed.
I rewrote the "Reproduce Steps" section and removed the heading because the content is for users, not QA.

2024-02-20 15:22 UTC, w13915984028 commented on docs/troubleshooting/monitoring.md
> +- The POD `prometheus-rancher-monitoring-prometheus-0` in `cattle-monitoring-system` namespace fails to start due to PVC attached failed.
BTW, somebody also has no interest of those `TL, DR` sections at first glance, they want to locate the `Workaround` directly.

2024-02-20 15:51 UTC, w13915984028 commented on docs/troubleshooting/monitoring.md
> +1. All pods are successfully deployed, the `rancher-monitoring` feature is avaiable.
`addon` is widerly used in both document https://docs.harvesterhci.io/v1.3/advanced/addons and Harvester UI

2024-03-15 06:34 UTC, jillian-maroket approved these changes
Approving only for GitHub workflow purposes. Many of the suggestions were rejected so the language quality is still not up to standard. This can be improved in another PR.

2024-03-15 06:37 UTC, innobead commented
> Approving only for GitHub workflow purposes. Many of the suggestions were rejected so the language quality is still not up to standard. This can be improved in another PR.

@w13915984028 :point_up:

2024-03-15 09:25 UTC, w13915984028 commented
Be easy. Let's recall the review and rework: @innobead 

There are 8 review comments from @jillian-maroket 

3,4,5,7,8: are fully accepted and updated.
2: Is updated, but not simply copied the words from suggestions.
6: Partially updated. As the original context has `50GiB` and `50Gi`, two different unit, the workaroud let user change `50` to `30`, but not touch the unit. The review suggestion is `Change the two `50` to `30` and save`.  
You may not notice this tiny difference, but we don't want the user to have additional change to import some other issues.
```
            retentionSize: 50GiB // Change 50 to 30
            storageSpec:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 50Gi // Change 50 to 30
                  storageClassName: harvester-longhorn
```

1: We have a disagreement about if a new chapter is needed, from practice I prefer it, and most words are kept. Assme this review point is rejected.


///
```
Many of the suggestions were rejected so the language quality is still not up to standard.
```

2024-03-15 11:52 UTC, innobead commented
Thanks @w13915984028 for the context. 

As mentioned, please discuss with @jillian-maroket directly to understand her feedback on why she felt the quality wasn't up to standard and how we can collaboratively improve it going forward. Our overall goal is to ensure consistently high-quality documentation.

> Approving only for GitHub workflow purposes. Many of the suggestions were rejected so the language quality is still not up to standard. This can be improved in another PR.

2024-03-18 02:25 UTC, jillian-maroket commented
@w13915984028 I don't have time to justify my edits to you, and frankly that's not my job. You assume that the original wording that you decide to keep is correct but you're wrong. Here's an example:

> Line 282: 1. Change the two `50` to `30` under prometheusSpec and save, the `promethues` feature will use `30GiB` disk to store data.

First, you misspelled Prometheus. Second, these should be two sentences so your usage of a comma is incorrect. Third, "change the two 50 to 30" wording is weird. It's very obvious that an non-native English speaker wrote the whole thing.

I spent so much time and effort in reviewing this PR (and all of your PRs) because the language was just not up to standard. If you reject my suggestions, that's all on you.

2024-03-18 21:44 UTC, markhillgit commented
@w13915984028 I've proposed some alternate wording. See if that works for you. if not, let's chat.

2024-03-19 01:42 UTC, markhillgit requested changes

2024-03-19 10:17 UTC, w13915984028 commented
Thanks @jillian-maroket @markhillgit, your time and efforts are very appreciated.

We get a better balance between technical correctness and beautiful languange.

2024-03-20 00:02 UTC, markhillgit approved these changes
thank you, lgtm

2024-03-20 00:03 UTC, merged